config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :places

  root 'places#index'

  namespace :backend do
    resources :places
  end

end

app/models/place.rb
class Place < ActiveRecord::Base
  validates :title, presence: true
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/backend/places_controller.rb
class Backend::PlacesController < ApplicationController
  before_action :set_place, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!

  # GET /places
  # GET /places.json
  def index
    @places = Place.all
  end

  # GET /places/1
  # GET /places/1.json
  def show
  end

  # GET /places/new
  def new
    @place = Place.new
  end

  # GET /places/1/edit
  def edit
  end

  # POST /places
  # POST /places.json
  def create
    @place = Place.new(place_params)

    respond_to do |format|
      if @place.save
        format.html { redirect_to backend_place_path(@place), notice: 'Place was successfully created.' }
        format.json { render :show, status: :created, location: @place }
      else
        format.html { render :new }
        format.json { render json: @place.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /places/1
  # PATCH/PUT /places/1.json
  def update
    respond_to do |format|
      if @place.update(place_params)
        format.html { redirect_to backend_place_path(@place), notice: 'Place was successfully updated.' }
        format.json { render :show, status: :ok, location: @place }
      else
        format.html { render :edit }
        format.json { render json: @place.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /places/1
  # DELETE /places/1.json
  def destroy
    @place.destroy
    respond_to do |format|
      format.html { redirect_to places_url, notice: 'Place was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_place
      @place = Place.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def place_params
      params.require(:place).permit(:title, :description, :youtube_link, :tagline, :xpos, :ypos, :image_file_name)
    end
end

app/controllers/places_controller.rb
class PlacesController < ApplicationController
  before_action :set_place, only: [:show, :edit, :update, :destroy]

  # GET /places
  # GET /places.json
  def index
    @places = Place.all
  end


end

app/helpers/application_helper.rb
module ApplicationHelper
  def mobile_device?
     if session[:mobile_param]
       session[:mobile_param] == "1"
     else
       request.user_agent =~ /Mobile|webOS/
     end
  end
end

app/helpers/places_helper.rb
module PlacesHelper
end

app/views/backend/places/_form.html.erb
<%= form_for [:backend, @place] do |f| %>
  <% if @place.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@place.errors.count, "error") %> prohibited this place from being saved:</h2>

      <ul>
      <% @place.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :tagline %><br>
    <%= f.text_field :tagline %>
  </div>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_area :description, size: "50x20" %>
  </div>
  <div class="field">
    <%= f.label :youtube_link %><br>
    <%= f.text_field :youtube_link %>
  </div>
  <div class="field">
    <%= f.label :xpos %><br>
    <%= f.text_field :xpos %>
  </div>
  <div class="field">
    <%= f.label :ypos %><br>
    <%= f.text_field :ypos %>
  </div>
  <div class="field">
    <%= f.label :image_file_name %><br>
    <%= f.text_field :image_file_name %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/backend/places/edit.html.erb
<h1>Editing Place</h1>

<%= render 'form' %>

<%= link_to 'Show', backend_place_path(@place) %> |
<%= link_to 'Back', backend_places_path %>

app/views/backend/places/index.html.erb
<% @places.each do |place| %>
<%= link_to place.title, backend_place_path(place) %>
<% end %>

app/views/backend/places/new.html.erb
<h1>New Place</h1>

<%= render 'form' %>

<%= link_to 'Back', places_path %>

app/views/backend/places/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @place.title %>
</p>

<p>
  <strong>Tagline:</strong>
  <%= @place.tagline.html_safe %>
</p>

<p>
  <strong>Description:</strong>
  <%= @place.description %>
</p>

<p>
  <strong>Youtube link:</strong>
  <%= @place.youtube_link %>
</p>
<p>
  <strong>Image file name:</strong>
  <%= @place.image_file_name %>
</p>

<%= link_to 'Edit', edit_backend_place_path(@place) %> |
<%= link_to 'Back', backend_places_path %>

app/views/layouts/_loader.html.erb
<div class="loader-wrapper">
    <div class="loader-inner">
      <h3>Demande à la nuit</h3>
      <div id="floatBarsG">
        <div id="floatBarsG_1" class="floatBarsG"></div>
        <div id="floatBarsG_2" class="floatBarsG"></div>
        <div id="floatBarsG_3" class="floatBarsG"></div>
        <div id="floatBarsG_4" class="floatBarsG"></div>
        <div id="floatBarsG_5" class="floatBarsG"></div>
        <div id="floatBarsG_6" class="floatBarsG"></div>
        <div id="floatBarsG_7" class="floatBarsG"></div>
        <div id="floatBarsG_8" class="floatBarsG"></div>
      </div>
    </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Demande à la nuit, le premier roman d'Anne Laure Jaeglé</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <meta name="description" content="Demande à la nuit vous plonge au coeur de la nuit berlinoise et du nouvel âge d'or que connait la techno. Un journal musical à l'écriture charnelle et incisive, rythmé par une soixantaine de morceaux. Le portrait d'une génération qui se trouve dans la fête. Disponible en librairies, ebook ou sur commande sur le site de la ville brûle..">
  <meta name="keywords" content="demande à la nuit, anne laure jaeglé, anne-laure jaeglé, berlin, techno, livre, book, music, musique, roman, house, lectures, la ville brûle, strasbourg, paris">
  <meta name="contact" content="axel.rigaud@gmail.com">
  <meta name="Author" content="Axel Rigaud">
  <meta name="Robots" content="all">
  <meta name="Distribution" content="Global">
  <meta name="Expires" content="Never">
</head>
<body>
  <h1>Demande à la nuit - Anne Laure Jaeglé</h1>


<%= yield %>

<div class="md-overlay"></div>
<div id="player"></div>
</body>
</html>

app/views/places/_about_modal.html.erb
<div class="md-modal md-effect-1" id="about-the-book">
  <div class="md-content">
    <h3 class="tagline">Demande à la nuit</h3>
    <p>
      « La rencontre de deux tracks est une rencontre amoureuse : là aussi il s’agit de vibrer à la même fréquence pour un temps donné, sans qu’une piste n’ait à s’ajuster plus que l’autre. »
    </p>
    <p>
      Anne Laure Jaeglé, passionnée de musique, organisatrice de soirées et de raves clandestines, vit à Berlin. 
    </p>
    <div>
      <div class="cover-container">
      </div>
    </div>
    <p>
      Disponible en librairies et sur commande à www.lavillebrule.com
    </p>
    <p>
      Playlists : www.youtube/demandealanuit
    </p>
    <div class="md-bottom">
    <a class="md-close">Fermer</a>
    </div>
  </div>
</div>

app/views/places/_form.html.erb
<%= form_for(@place) do |f| %>
  <% if @place.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@place.errors.count, "error") %> prohibited this place from being saved:</h2>

      <ul>
      <% @place.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :tagline %><br>
    <%= f.text_field :tagline %>
  </div>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_area :description %>
  </div>
  <div class="field">
    <%= f.label :youtube_link %><br>
    <%= f.text_field :youtube_link %>
  </div>
  <div class="field">
    <%= f.label :xpos %><br>
    <%= f.text_field :xpos %>
  </div>
  <div class="field">
    <%= f.label :ypos %><br>
    <%= f.text_field :ypos %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/places/_loader.html.erb
<div class="loader-wrapper">
  <div class="cube">
    <div class="face front"></div>
    <div class="face back"></div>
    <div class="face left"></div>
    <div class="face right"></div>
    <div class="face top"></div>
    <div class="face bottom"></div>
  </div>
</div>

app/views/places/_place_modal.html.erb
<div class="md-modal md-effect-1" id="<%=place.title%>">
  <div class="md-content">
    <h3 class="tagline"><%= place.tagline.html_safe %></h3>
    <%= render 'cross' %>
    <div>
      <p class="excerpt">
        <%= place.description %>
      </p>
      <div class="md-bottom">
        
        <a class="md-about" href="#">À propos du livre...</a>
      </div>
    </div>
  </div>
</div>

app/views/places/_welcome_modal.html.erb
<div class="md-modal md-effect-1" id="welcome">
  <div class="md-content">
    <h3 class="tagline">Demande à la nuit</h3>
    <div>
      <p class="excerpt">
      Bienvenue sur le site consacré au premier roman d'Anne Laure Jaeglé, Demande à la Nuit.<br>
      Parcourez la carte de Berlin pour découvrir des extraits du livre.
    </p>
    </div>
    
    <div class="md-bottom">
      <a class="md-close">Fermer</a>
    </div>
  </div>
</div>

app/views/places/index.html.erb
<%= render 'loader' %>

  <div class="header__container">
  </div>

    <% @places.each do |place| %>
      <%= render 'place_modal', place: place %>
    <% end %>

    <div class="map">
      <div class="map-inner">
        <% @places.each.with_index do |place, index| %>
          <%= link_to('#', {style:"left: #{place.xpos}%;top: #{place.ypos}%;", class:"md-trigger place-link delay-#{index}", data: {modal: 'modal-1', target: "##{place.title}", youtube: "#{place.youtube_link}"}, onclick:"ga('send', 'event', 'place-link', 'click','#{place.title}');"}) do %>
            <% if mobile_device? %>
              <%= image_tag(place.image_file_name+'.png') %>
            <% else %>
              <%= image_tag(place.image_file_name+'@2x.png') %>
            <% end %>
          <% end %>
        <% end %>
      </div>
    </div>
<section id="about-the-book">
  <div class="container">
    <header class="section__header">
      À propos du livre
    </header>
  </div>
  <div class="quote__container owl-carousel">
    <div>
      <p class="quote__content">
        "Rythmé par une bande son en or, ce livre transporte."
      </p>
      <p class="quote__author">
        le Bonbon
      </p>
    </div>
    <div>
      <p class="quote__content">
        "Magistral."
      </p>
      <p class="quote__author">
        Trax Magazine
      </p>
    </div>
    <div>
      <p class="quote__content">
        "À côté, Bret Easton Ellis, c'est Barbara Cartland."
      </p>
      <p class="quote__author">
        Frédéric Beigbeder
      </p>
    </div>
  </div>
  <div class="container">
    <div class="row story__container">
      <div class="story__book col-md-3">
        <%= image_tag('livre-pliage.jpg') %>
      </div>
      <div class="col-md-7 col-md-offset-1">
        <p class="story__text">
          Demande à la nuit vous plonge au coeur de la nuit
          berlinoise et du nouvel âge d'or que connait la techno.
          Un "journal musical" à l'écriture charnelle et incisive, rythmé par une soixantaine de morceaux.
          Le portrait d'une génération qui se trouve dans la fête.
        </p>
        <p class="story__find-it">
          Disponible en librairies, ebook ou sur commande sur le site de <a href="http://www.lavillebrule.com/catalogue/demande-a-la-nuit,80" onclick="trackOutboundLink('http://www.lavillebrule.com/catalogue/demande-a-la-nuit,80'); return false;">la ville brûle</a>.
        </p>
      </div>
    </div>
    <div class="row author__container">
      <div class="col-md-6 col-md-offset-1 author__left-block">
        <p class="author__title">
          l'auteure
        </p>
        <p class="author__bio">
          Anne Laure Jaeglé, passionnée de musique, organisatrice de soirées et de raves clandestines, vit à Berlin.
          Demande à la nuit est son premier roman.
        </p>
      </div>
      <div class="col-md-4 author__photo">
        <%= image_tag('anne-laure.jpg') %>
      </div>
    </div>
</section>
<section id="lectures">
  <div class="container">
    <h3 class="lectures__header">Lectures électroniques</h3>
    <p class="lectures__body">Demande à la Nuit est aussi une performance live mêlant lecture et musique.</p>
    <div class="row">
      <div class="col-md-6"><a class="lectures__link" href="https://www.youtube.com/watch?v=JyzlMWTjmJg">Teaser Vidéo</a></div>

      <div class="col-md-6"><a class="lectures__link" href="https://drive.google.com/open?id=0B2Kjl8yB2VNSM2dFN09IZ0lWVDA">Dossier de Presse</a></div>
    </div>
  </div>

</section>
<footer class="footer">
  <p class="footer__text">Tous droits réservés. Texte et illustrations d'Anne Laure Jaeglé. Design & Code : <a href="http://www.axelrigaud.com" onclick="trackOutboundLink('http://www.axelrigaud.com'); return false;">Axel Rigaud</a>.</p>
</footer>
<%= javascript_include_tag :frontend %>
<script>
  (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
  (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
  m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
  })(window,document,'script','https://www.google-analytics.com/analytics.js','ga');

  ga('create', 'UA-47225573-5', 'auto');
  ga('send', 'pageview');

  var trackOutboundLink = function(url) {
   ga('send', 'event', 'outbound', 'click', url, {'hitCallback':
     function () {
     document.location = url;
     }
   });
  }

</script>